version: '3'

services:
  contenedor1:
    build: ./contenedor1
    ports:
      - "5000:5000"
    networks:
      - my_network

  contenedor2:
    build: ./contenedor2
    depends_on:
      - contenedor1
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
